sudo: required

dist: trusty

env:
  - VERSION=9.3
  - VERSION=9.4

before_install:
  - sudo apt-get -y purge docker-engine
  - bash <(curl -fsSL https://get.docker.com/)
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" nanobox
  - ifconfig
  - echo building $VERSION
  - docker pull nanobox/postgresql:$VERSION

script: sudo test/run_all.sh $VERSION